#! /bin/bash

DELIM=','
while getopts h?f:r:p: OPT; do
    case $OPT in
        \?|h)
echo "csv-sample: Randomly sample a proportion of a delimited file."
echo
echo "usage: csv-sample [-r HEADER_FILE] -f FILE -p PROPORTION"
echo
echo "required arguments:"
echo "  -f FILE           Delimited file. Must be supplied from a"
echo "                    file instead of a stream, as down sampling"
echo "                    takes two passes over the data."
echo "  -p PROPORTION     Numerical proportion of records to sample,"
echo "                    for example .5 or .75."
echo
echo "optional arguments:"
echo "  -r HEADER_FILE    Header file containing the column names"
echo "                    for the delimited file. If not supplied,"
echo "                    it is assumed that the first line of the"
echo "                    input file contains the header information."
echo "                    While sampling do not require the header,"
echo "                    it must know whether the first line in the"
echo "                    data contains the header or data."
            exit 0
            ;;
        f)
            FILE=$OPTARG
            ;;
        r)
            HEADERFILE=$OPTARG
            ;;
        p)
            PROP=$OPTARG
            ;;
    esac
done

if [[ $FILE == '' ]]; then
    echo "csv-sample: Argument -f required." >&2
    exit 1
fi
if [[ $PROP == '' ]]; then
    echo "csv-sample: Argument -p required." >&2
    exit 1
fi

# Count the number of records in the file, then offset by one if
# the header is included.
NREC=$(cat $FILE | wc -l)
if [[ $HEADERFILE == '' ]]; then
    NREC=$(echo "$NREC - 1" | bc -l)
fi

# cut -d. -f1 == floor
NTOTAKE=$(echo "$NREC * $PROP" | bc -l | cut -d. -f1)

# Output the header if its neccessary
if [[ $HEADERFILE == '' ]]; then
    TAILARG='+2'
    cat $FILE | head -1
else
    TAILARG='+1'
fi

cat $FILE | tail -n $TAILARG | shuf -n $NTOTAKE

exit 1
