#! /bin/bash

while getopts h:r:T:d?u?i? OPT; do
    case $OPT in
        \?|h)
echo "csv-set: Perform set operations on delimited files by row."
echo
echo "usage: csv-set [-T TEMP_DIR] [-r HEADER_FILE]"
echo "               (-d | -u | -i) FILE1 FILE2"
echo
echo "required arguments:"
echo "  FILE1             Delimited file."
echo "  FILE2             Delimited file."
echo
echo "exactly one of the following is also required."
echo "  -d                Take the difference to two files. I.e."
echo "                    output all records in FILE1 and not in"
echo "                    FILE2."
echo "  -u                Take the union of two files. I.e. output"
echo "                    all the records that exsist in either"
echo "                    FILE1 or FILE2."
echo "  -i                Take the intersection of two files. I.e."
echo "                    output all the records that exist in both"
echo "                    FILE1 and FILE2."
echo 
echo "optional arguments:"
echo "  -T TEMP_DIR       Specify a directory to use for scratch"
echo "                    space during sorting. If not supplied,"
echo "                    /tmp is assumed."
echo "  -r HEADER_FILE    Header file containing the column names"
echo "                    for the delimited file. If not supplied,"
echo "                    it is assumed that the first line of the"
echo "                    input file contains the header information."
echo "                    While set operations do not require the"
echo "                    header, they need to know whether the first"
echo "                    line in the files contain te header or data."
            exit 0
            ;;
        r)
            HEADERFILE=$OPTARG
            ;;
        d)
            TYPE="DIFF"
            ;;
        u)
            if [[ $TYPE != '' ]]; then
                echo "Only one operation type argument may be supplied at a time." &>2
                exit 1
            fi
            TYPE="UNION"
            ;;
        i)
            if [[ $TYPE != '' ]]; then
                echo "Only one operation type argument may be supplied at a time." &>2
                exit 1
            fi
            TYPE="INTERSECTION"
            ;;
        T)
            TEMPDIR=$OPTARG
            ;;
    esac
done

if [[ $TYPE == '' ]]; then
    echo "csv-set: No or unknown operation supplied."
    exit 1
fi

if [[ $TEMPDIR != '' ]]; then
    SORTARGS="-T $TEMPDIR"
fi

shift $(($OPTIND - 1))
THIS=$1
THAT=$2

# Headerfile is an optional argument, if not supplied it is assumed that the
# first line of the file is a header
if [[ $HEADERFILE == '' ]]; then
    HEADERFILE1=$THIS; HEADERFILE2=$THAT
    HEADER1=$(cat $HEADERFILE1 | head -1)
    HEADER2=$(cat $HEADERFILE2 | head -1)
    if [[ $HEADER1 != $HEADER2 ]]; then
        echo "Headers in two files not equal, aborting." >&2
        exit 1
    fi
    HEADER=$HEADER1; HEADERFILE=$THIS
    TAILARG="+2"
else
    TAILARG="+1"
fi

if [[ $HEADERFILE == $THIS ]]; then
    echo $HEADER
fi

if [[ $TYPE == "DIFF" ]]; then
    diff <(cat $THIS | tail -n $TAILARG | sort $SORTARGS) \
         <(cat $THAT | tail -n $TAILARG | sort $SORTARGS) \
        | grep '< ' \
        | sed 's!< !!'
elif [[ $TYPE == "UNION" ]]; then
    cat <(cat $THIS | tail -n $TAILARG) <(cat $THAT | tail -n $TAILARG) \
        | sort $SORTARGS \
        | uniq
elif [[ $TYPE == "INTERSECTION" ]]; then
    comm -12 <(cat $THIS | tail -n $TAILARG | sort $SORTARGS) \
             <(cat $THAT | tail -n $TAILARG | sort $SORTARGS)
else
    echo "csv-set: Type not recognized." >&2
    exit 1
fi

exit 0
