#! /bin/bash
SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DELIM=','
QUO='"'
while getopts h?d:f:c:p:r:v? OPT; do
    case $OPT in
        \?|h)
            echo "csv-grep: select rows from a csv acocrding to a pattern."
            echo "useage:"
            echo "  csv-grep -f <delimited file> [-d <delim>] [-q <quoting char>]"\
                 "[-r <header file>] -c <column name or index> -p <pattern>"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        q)
            QUO=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
        r)
            HEADERFILE=$OPTARG
            ;;
        c)
            COL=$OPTARG
            ;;
        p)
            PATTERN=$OPTARG
            ;;
        v)
            REVERSEMATCH=1
            ;;
    esac
done


if [[ $COL == '' ]]; then
    echo "csv-grep: Argument -c required." >&2
    exit 1
fi
if [[ $PATTERN == '' ]]; then
    echo "csv-grep: Argument -p required." >&2
    exit 1
fi
# Reverse match is optional.
if [[ $REVERSEMATCH == '' ]]; then
    REVERSEMATCH=0
fi
# Explicit file argument is optional, if not supplied it is assumed the 
# file is streaming from standard input
if [[ $FILE == '' ]]; then
    FILE="stdin"
fi
# Header argument is optional, if not supplied it is assumed to be the 
# first line in FILE.
if [[ $HEADERFILE == '' ]]; then
    HEADERFILE=$FILE
fi

# We need to get the actual header to keep so it does not interfere
# with our grepping.  How to do this depends on whether we are working from 
# standard input, or from a file.
if [[ $HEADERFILE != $FILE ]]; then
    HEADER=$(cat $HEADERFILE | head -1)
    NROWTOSKIP=0
elif [[ $FILE == "stdin" ]]; then
    read HEADER
    NROWTOSKIP=0
else
    HEADER=$(cat $HEADERFILE | head -1)
    NROWTOSKIP=1
fi

# Check if the column array is numeric id's, if not, parse the array of names
# to get the numeric indicies of the named columns
if [[ $COL =~ [0-9] ]]; then
    COLIDX=$COL
else
    COLIDX=$(csv-getcolidx -r $HEADER -d $DELIM -c $COL)
    if [[ $? != 0 ]]; then
        echo "csv-grep: Could not find indicies for some of the requested columns." >&2
        echo "Are you sure they all exist?" >&2
        exit 1
    fi
fi

if [[ $HEADERFILE == $FILE ]]; then
    echo $HEADER
fi

if [[ $FILE != 'stdin' ]]; then
    $SRCDIR/bin/grep $FILE $DELIM $QUO $NROWTOSKIP $REVERSEMATCH $COLIDX $PATTERN
else
    cat /dev/stdin \
        | $SRCDIR/bin/grep $FILE $DELIM $QUO $NROWTOSKIP $REVERSEMATCH $COLIDX $PATTERN
fi

exit 0
