#! /bin/bash

DELIM=','
while getopts h?d:f: OPT; do
    case $OPT in
        \?|h)
            echo "csv-validate: Check if a delimited file is well specified"
            echo "useage:"
            echo "  csv-validate -f <delimited file> [-d <delim>]"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

echo "The following number of delimiters per line were found."
cat $FILE | head -1 | tr -dc "$DELIM\n" | sort | uniq -c | tr -d "$DELIM"
