#! /bin/bash
SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DELIM=','
QUO='"'
while getopts h?d:q:f: OPT; do
    case $OPT in
        \?|h)
            echo "csv-cut: Cut columns out of a csv."
            echo "useage:"
            echo "  csv-cut -f <delimited file> [-d <delim>] [-q <quoting char>"
            echo "          <array of column names>"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        q)
            QUO=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

# Get the column indexes of the requested columns.
COLIDXS=$(csv-getcolidxs -f $FILE -d $DELIM ${@:1})
if [[ $? != 0 ]]; then
    exit 1
fi

# Sort the column indiexs
COLIDXS=$(echo $COLIDXS | tr ' ' '\n' | sort -n | tr '\n' ' ')

# Check if duplicate columns were requested.
DUPS=$(echo $COLIDXS | tr ' ' '\n' | uniq -d)
if [[ $DUPS != '' ]]; then
    echo "Duplicate columns detected, terminating." >&2
    echo 1
fi

# Call the binary.
if [[ $QUO == '"' ]]; then
   $SRCDIR/bin/cut $FILE $DELIM '"' $COLIDXS
elif [[ $QUO == "'" ]]; then
   $SRCDIR/bin/cut $FILE $DELIM "'" $COLIDXS
else
   $SRCDIR/bin/cut $FILE $DELIM $QUO $COLIDXS
fi
