#! /bin/bash
DELIM=','
QUO='"'
while getopts h?d:f:c:p: OPT; do
    case $OPT in
        \?|h)
            echo "csv-hist: Make a frequency table from columns in a csv."
            echo "useage:"
            echo "  csv-hist -f <delimited file> [-d <delim>] [-q <quoting char>]"\
                 "<column 1 name> ... <column n name>                 "
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        q)
            QUO=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

if [[ $FILE == '' ]]; then
    echo "csv-hist: Argument -f required." >&2
    exit 1
fi

shift $(($OPTIND - 1))
COLS="${@:1}"
if [[ $COLS == '' ]]; then
    echo "csv-hist: No columns to summarize." >&2
    exit 1
fi

csv-cut -f $FILE -d $DELIM -q $QUO $COLS \
  | tail -n +2 \
  | sort \
  | uniq -c
