#! /bin/bash
SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

QUO='"'
while getopts h?d:n:q:f: OPT; do
    case $OPT in
        \?|h)
            echo "csv-ch-delim: Change the delimiter in a file."
            echo "useage:"
            echo "  csv-chdelim -f <file> -d <delimiter> -n <new dilimiter>"
            echo "              [-q <quoting char>]"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        n)
            NEWDELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
        q)
            QUO=$OPTARG
            ;;
    esac
done

if [[ $DELIM == '' ]]; then
    echo "csv-chdelim: Argument -d required." >&2
    exit 1
fi
if [[ $NEWDELIM == '' ]]; then
    echo "csv-chdelim: Argument -n required." >&2
    exit 1
fi

# Explicit file argument is optional, if not supplied it is assumed the 
# file is streaming from standard input
if [[ $FILE == '' ]]; then
   cat /dev/stdin | $SRCDIR/bin/chdelim "stdin" $DELIM $NEWDELIM $QUO
else
   $SRCDIR/bin/chdelim $FILE $DELIM $NEWDELIM $QUO
fi

exit 0
