#! /bin/bash
SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

QUO='"'
while getopts h?d:n:q:f: OPT; do
    case $OPT in
        \?|h)
echo "csv-chdelim: Change the delimiter in a delimited file."
echo
echo "useage: csv-chdelim [-f FILE] [-q QUOTING_CHAR] -d DELIMITER "
echo "                    -n NEW_DELIMITER"
echo 
echo "required arguments:"
echo "  -d DELIMITER      Character delimiting the input file."
echo "  -n NEW_DELIMITER  Character to change delimiter to."
echo
echo "optional arguments:"
echo "  -f FILE           Delimited file. If not supplied input is"
echo "                    Read from the standard input stream."
echo "  -q QUOTING_CHAR   Character used for quoting fileds in the"
echo "                    file. If not supplied, assumed to be"
echo "                    double quotes"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        n)
            NEWDELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
        q)
            QUO=$OPTARG
            ;;
    esac
done

if [[ $DELIM == '' ]]; then
    echo "csv-chdelim: Argument -d required." >&2
    exit 1
fi
if [[ $NEWDELIM == '' ]]; then
    echo "csv-chdelim: Argument -n required." >&2
    exit 1
fi

# Explicit file argument is optional, if not supplied it is assumed the 
# file is streaming from standard input
if [[ $FILE == '' ]]; then
   cat /dev/stdin | $SRCDIR/bin/chdelim "stdin" $DELIM $NEWDELIM $QUO
else
   $SRCDIR/bin/chdelim $FILE $DELIM $NEWDELIM $QUO
fi

exit 0
