#! /bin/bash

# Parse command line args
DELIM=','
while getopts h?r:d:c: OPT; do
    case $OPT in
        \?|h)
            echo "csv-getcolidx:  Get the index of a column in a delimited file."
            echo "useage:"
            echo "  csv-getcolidx -r <header string> -c <column name> [-d <delim>]"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        r)
            HEADER=$OPTARG
            ;;
        c)
            COL=$OPTARG
            ;;
    esac
done

if [[ $HEADER == '' ]]; then
    echo "csv-getcolidx: argument -r required" >&2
    exit 1
fi
if [[ $COL == '' ]]; then
    echo "csv-getcolidx: argument -c required" >&2
    exit 1
fi

COLIDX=$(echo $HEADER | sed "s!$DELIM!\n!g" | grep -nx $COL | cut -d: -f 1)

if [[ $COLIDX == '' ]]; then
    echo "csv-getcolidx: Column $COL not found.  Terminating." >&2
    exit 1
fi

# grep -n counts starting at one, we require starting at 0.
echo "$COLIDX - 1" | bc
exit 0
