#! /bin/bash

DELIM=','
while getopts h?d:f: OPT; do
    case $OPT in
        \?|h)
            echo "csv-diff: Take lines in one file but not in another."
            echo "useage:"
            echo "  csv-diff [-d <delim>] <this> ('minus') <that>"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

THIS=$1
THAT=$2

{ cat $THIS | head -1 ;
  diff <(cat $THIS | tail -n +2 | sort) <(cat $THAT | tail -n +2 | sort) \
    | grep '< ' \
    | sed 's!< !!' ; \
}
