#! /bin/bash

# Parse command line args
DELIM=','
while getopts h?f:d:c: OPT; do
    case $OPT in
        \?|h)
            echo "csv-getcolidxs:  Get the indices of multiple columns in a delimited file."
            echo "useage:"
            echo "  csv-getcolidxs -f <delimited file> [-d <delim>] <column names>"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

# Shift the argument pointer so that the passed coumns are stored in $1, $2, etc
shift $(($OPTIND - 1))

out_str=""
for COLNM in ${@:1}; do
  COLIDX=$(csv-getcolidx -d $DELIM -f $FILE -c $COLNM)

  if [[ $? != 0 ]]; then
      echo "csv-getcolidxs: Field $COLNM not found, terminating."
      exit 1
  fi

  out_str="$out_str,$COLIDX"
done;

echo $out_str | sed "s/,//" | sed "s/,/ /g"
exit 0
