#! /bin/bash

DELIM=','
while getopts h?d:f: OPT; do
    case $OPT in
        \?|h)
            echo "csv-cut: Cut columns out of a csv."
            echo "useage:"
            echo "  csv-cut -f <delimited file> [-d <delim>] <column names>"
            exit 0
            ;;
        d)
            DELIM=$OPTARG
            ;;
        f)
            FILE=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

COLIDXS=$(csv-getcolidxs -f $FILE -d $DELIM ${@:1})
cat $FILE | cut -d $DELIM -f $COLIDXS 
