#! /bin/bash

DELIM=','
while getopts h:f:p: OPT; do
    case $OPT in
        \?|h)
            echo "csv-sample: Randomly sample a proportion of a data set."
            echo "useage:"
            echo "  csv-sample -f <delimited file> [-d <delim>] -p <proportion>"
            exit 0
            ;;
        f)
            FILE=$OPTARG
            ;;
        p)
            PROP=$OPTARG
            ;;
    esac
done

if [[ $FILE == '' ]]; then
    echo "csv-sample: Argument -f required." >&2
    exit 1
fi
if [[ $PROP == '' ]]; then
    echo "csv-sample: Argument -p required." >&2
    exit 1
fi

NREC=$(cat $FILE | tail -n +2 | wc -l)
NTOTAKE=$(echo "$NREC * $PROP" | bc -l | cut -d. -f1)

{ cat $FILE | head -1 ; \
  cat $FILE | tail -n +2 | shuf -n $NTOTAKE ; \
}
